	
	CREATE TABLE SY_LCTR 
	 ( SL_SEQ              			int(11) NOT NULL AUTO_INCREMENT COMMENT '수업일련번호'
	 , ST_SEQ              			int(11)  						COMMENT '템플릿일련번호'
	 , SL_TITLE            			VARCHAR(2000) NOT NULL 			COMMENT '수업명'
	 , SL_ID						VARCHAR(2000) NOT NULL   		COMMENT '수업ID(URL)'
	 , SL_LIBR_PB_YN       			CHAR(1) NOT NULL 				COMMENT '라이브러리공유여부'  
	 , SL_TAG						VARCHAR(400) 					COMMENT '수업태그'
	 , SL_RDCN						int(11) 						COMMENT '수업조회수'
	 , SL_DELE_YN					CHAR(1) NOT NULL DEFAULT 'N'	COMMENT'수업삭제여부'											
	 , SL_INPUT_TY 					VARCHAR(20) NOT NULL    		COMMENT '등록자유형코드(USER_TY_CD)'
	 , SL_INPUT_ID 					VARCHAR(100) NOT NULL   		COMMENT '등록자ID'
	 , SL_INPUT_NM 					VARCHAR(100) NOT NULL   		COMMENT '등록자명'
	 , SL_INPUT_DT 					DATE NOT NULL            		COMMENT '등록일시'
	 , SL_INPUT_IP 					VARCHAR(100) NOT NULL   		COMMENT '등록자IP'
	 , SL_MODER_TY 					VARCHAR(20)             		COMMENT '수정자유형코드(USER_TY_CD)'
	 , SL_MODER_ID 					VARCHAR(100)            		COMMENT '수정자ID'
	 , SL_MODER_NM 					VARCHAR(100)            		COMMENT '수정자명'
	 , SL_MODER_DT 					DATE                     		COMMENT '수정일시'
	 , SL_MODER_IP 					VARCHAR(100)            		COMMENT '수정자IP'
	
	 );
	

	CREATE TABLE SY_RESR
	 ( SR_SEQ 						int(11) NOT NULL AUTO_INCREMENT COMMENT '리소스일련번호'
	 , SR_SJ            			VARCHAR2(2000) NOT NULL 		COMMENT '리소스제목'
	 , SR_DC						VARCHAR(400)                    COMMENT '리소스설명'
	 , SR_RE_TY_CD					VARCHAR(20)						COMMENT '리소스유형(RESR_TY_CD)'
	 , SR_LIBR_PB_YN       			CHAR(1) NOT NULL 				COMMENT '라이브러리공유여부'
	 , SR_MV_URL
	 , SR_IMAG_URL
	 , SR__WEB_URL
     , SR_URL														COMMENT '리소스URL'
     , SR_POST_CN					CLOB							COMMENT '리소스포스팅 내용'
     , SR_FILE_SEQ					int(11) NOT NULL AUTO_INCREMENT	COMMENT '리소스첨부파일SEQ'   
     , SR_SC_FIXE_YN				CHAR(1)  DEFAULT 'Y'			COMMENT '리소스 사이즈 화면맞춤여부'
     , SR_BT						COMMENT '리소스 너비'
     , SR_HG						COMMENT '리소스 높이'

	 , SR_INPUT_TY 					VARCHAR(20) NOT NULL    		COMMENT '등록자유형코드(USER_TY_CD)'
	 , SR_INPUT_ID 					VARCHAR(100) NOT NULL  			COMMENT '등록자ID'
	 , SR_INPUT_NM 					VARCHAR(100) NOT NULL   		COMMENT '등록자명'
	 , SR_INPUT_DT 					DATE NOT NULL            		COMMENT '등록일시'
	 , SR_INPUT_IP 					VARCHAR(100) NOT NULL   		COMMENT '등록자IP'
	 , SR_MODER_TY 					VARCHAR(20)             		COMMENT '수정자유형코드(USER_TY_CD)'
	 , SR_MODER_ID 					VARCHAR(100)            		COMMENT '수정자ID'
	 , SR_MODER_NM 					VARCHAR(100)            		COMMENT '수정자명'
	 , SR_MODER_DT 					DATE                     		COMMENT '수정일시'
	 , SR_MODER_IP 					VARCHAR(100)            		COMMENT '수정자IP'
	 );
	
	 
	CREATE TABLE SY_LCTR_RESR
	(
	  SL_SEQ              		int(11) NOT NULL AUTO_INCREMENT COMMENT '수업일련번호'   --> fk,
	  SR_SEQ 					int(11) NOT NULL AUTO_INCREMENT COMMENT '리소스일련번호'--> fk
	  SLR_SCHU_CD 				VARCHAR(20) 					COMMENT'학교코드(DETA_CL_CD)'
	  SLR_GRAD_CD 				VARCHAR(20) 					COMMENT'학년코드(DETA_CL_CD)'
	  SLR_SMES_CD 				VARCHAR(20) 					COMMENT'학기코드(DETA_CL_CD)' 
	  SLR_SUBJ_CD 				VARCHAR(20) 					COMMENT'과목코드(DETA_CL_CD)'
	  SLR_UNIT_CD 				VARCHAR(20) 					COMMENT'단원코드(DETA_CL_CD)'
	  SLR_TM_CD 				VARCHAR(20) 					COMMENT'차시코드(DETA_CL_CD)'
	);
	 
	
	
	CREATE TABLE SY_TMPL
	( ST_SEQ              			int(11) NOT NULL AUTO_INCREMENT COMMENT '템플릿일련번호'   
	, ST_USE_COUNT				    int(11) 						COMMENT '템플릿이용횟수'
	, ST_CL_CD               			COMMENT '템플릿 분류 코드 EX)국어,수학,겨울방학'
	, ST_INPUT_TY 					VARCHAR(20) NOT NULL    COMMENT '등록자유형코드(USER_TY_CD)'
	, ST_INPUT_ID 					VARCHAR(100) NOT NULL   COMMENT '등록자ID'
	, ST_INPUT_NM 					VARCHAR(100) NOT NULL   COMMENT '등록자명'
	, ST_INPUT_DT 					DATE NOT NULL            COMMENT '등록일시'
	, ST_INPUT_IP 					VARCHAR(100) NOT NULL   COMMENT '등록자IP'
	, ST_MODER_TY 					VARCHAR(20)             COMMENT '수정자유형코드(USER_TY_CD)'
	, ST_MODER_ID 					VARCHAR(100)            COMMENT '수정자ID'
	, ST_MODER_NM 					VARCHAR(100)            COMMENT '수정자명'
	, ST_MODER_DT 					DATE                     COMMENT '수정일시'
	, ST_MODER_IP 					VARCHAR(100)            COMMENT '수정자IP'
	);
	
	CREATE TABLE SY_COMN_LYOT
	( SCL_SEQ              			int(11) NOT NULL AUTO_INCREMENT COMMENT '레이아웃일련번호'
	, SR_SEQ						int(11) 						COMMENT '리소스일련번호' 														
	, SCL_TY														COMMENT '레이아웃타입' EX) 공통 8개(DEFAULT), 포스팅
	, SCL_SHAP						COMMENT '레이아웃 구조'
	, SCL_INPUT_TY 					VARCHAR(20) NOT NULL    COMMENT '등록자유형코드(USER_TY_CD)'
	, SCL_INPUT_ID 					VARCHAR(100) NOT NULL   COMMENT '등록자ID'
	, SCL_INPUT_NM 					VARCHAR(100) NOT NULL   COMMENT '등록자명'
	, SCL_INPUT_DT 					DATE NOT NULL            COMMENT '등록일시'
	, SCL_INPUT_IP 					VARCHAR(100) NOT NULL   COMMENT '등록자IP'
	, SCL_MODER_TY 					VARCHAR(20)             COMMENT '수정자유형코드(USER_TY_CD)'
	, SCL_MODER_ID 					VARCHAR(100)            COMMENT '수정자ID'
	, SCL_MODER_NM 					VARCHAR(100)            COMMENT '수정자명'
	, SCL_MODER_DT 					DATE                     COMMENT '수정일시'
	, SCL_MODER_IP 					VARCHAR(100)            COMMENT '수정자IP'
	);
	
	CREATE TABLE SY_COMM_LYOT_TY
	( 
	  SLC_SEQ		
	  SCL_TY 
	  	 );
	
	 
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('DETA_CL_CD','MA_CODE','상세분류코드',NULL,'상세분류코드','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'MA_COD'),'master',SYSDATE,'master','master');
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('SLR_SCHU_CD','DETA_CL_CD','학교코드',NULL,'학교코드','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'DETA_CL_CD'),'master',SYSDATE,'master','master');
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('SLR_GRAD_CD','DETA_CL_CD','학년코드',NULL,'학년코드','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'DETA_CL_CD'),'master',SYSDATE,'master','master');
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('SLR_SMES_COD','DETA_CL_CD','학기코드',NULL,'학기코드','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'DETA_CL_CD'),'master',SYSDATE,'master','master');
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('SLR_SUBJ_COD','DETA_CL_CD','학기코드',NULL,'과목코드','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'DETA_CL_CD'),'master',SYSDATE,'master','master');
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('SLR_UNIT_COD','DETA_CL_CD','단원코드',NULL,'단원코드','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'DETA_CL_CD'),'master',SYSDATE,'master','master');
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('SLR_TM_CD','DETA_CL_CD','차시코드',NULL,'차시코드','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'DETA_CL_CD'),'master',SYSDATE,'master','master');
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('001','SLR_CHU_CD','초등학교',NULL,'초등학교','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_SCHU_CD'),'master',SYSDATE,'master','master');
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('002','SLR_CHU_CD','중학교',NULL,'중학교','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_SCHU_CD'),'master',SYSDATE,'master','master');
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('003','SLR_CHU_CD','고등학교',NULL,'고등학교','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_SCHU_CD'),'master',SYSDATE,'master','master');	
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('01','SLR_GRAD_CD','1학년',NULL,'1학년','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_GRAD_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('02','SLR_GRAD_CD','2학년',NULL,'2학년','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_GRAD_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('03','SLR_GRAD_CD','3학년',NULL,'3학년','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_GRAD_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('04','SLR_GRAD_CD','4학년',NULL,'4학년','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_GRAD_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('05','SLR_GRAD_CD','5학년',NULL,'5학년','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_GRAD_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('06','SLR_GRAD_CD','6학년',NULL,'6학년','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_GRAD_CD'),'master',SYSDATE,'master','master');


	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('1','SLR_SBJE_CD','1학기',NULL,'1학기','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_SBJE_CD'),'master',SYSDATE,'master','master');
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('2','SLR_SBJE_CD','2학기',NULL,'2학기','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_SBJE_CD'),'master',SYSDATE,'master','master');
	
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('01','SLR_UNIT_CD','1단원',NULL,'1단원','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_UNIT_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('02','SLR_UNIT_CD','2단원',NULL,'2단원','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_UNIT_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('03','SLR_UNIT_CD','3단원',NULL,'3단원','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_UNIT_CD'),'master',SYSDATE,'master','master');
	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('001','SLR_TM_CD','1차시',NULL,'1차시','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_TM_CD'),'master',SYSDATE,'master','master');	
	 INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('001','SLR_TM_CD','2차시',NULL,'1차시','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SLR_TM_CD'),'master',SYSDATE,'master','master');
	
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('SR_RE_TY_COD','RESR_TY_CD','리소스유형코드',NULL,'리소스유형코드','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'RESR_TY_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('001','SR_RE_TY_CD','동영상',NULL,'동영상','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SR_RE_TY_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('002','SR_RE_TY_CD','이미지',NULL,'이미지','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SR_RE_TY_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('003','SR_RE_TY_CD','웹페이지',NULL,'웹페이지','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SR_RE_TY_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('004','SR_RE_TY_CD','포스팅',NULL,'포스팅','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SR_RE_TY_CD'),'master',SYSDATE,'master','master');
	INSERT INTO MA_CODE(CD_ID,UP_CD_ID,CD_KO_NM,CD_EN_NM,CD_INFO_ST,CD_INFO_ND,USE_YN,SO_OR,INPUT_ID,INPUT_DT,INPUT_NM,INPUT_IP
	)VALUES('005','SR_RE_TY_CD','PDF/PPT',NULL,'PDF/PPT','','1',(SELECT NVL(MAX(SO_OR), 0) + 1 FROM MA_CODE WHERE UP_CD_ID = 'SR_RE_TY_CD'),'master',SYSDATE,'master','master');
	
	